import type { Prisma } from "@prisma/client";

export type SensitiveAction =
  | "ADMIN_LOGIN"
  | "EMPLOYER_REGISTERED"
  | "EMPLOYER_ACCOUNT_UPDATED"
  | "EMPLOYER_PASSWORD_CHANGED"
  | "CANDIDATE_REGISTERED_WITH_CONSENT"
  | "LGPD_REQUEST_CREATED"
  | "MANUAL_PIX_PAYMENT_CREATED"
  | "MANUAL_PIX_PAYMENT_CONFIRMED"
  | "ADMIN_USER_CREATED"
  | "ADMIN_USER_ROLE_UPDATED"
  | "ADMIN_USER_BLOCKED"
  | "ADMIN_USER_UNBLOCKED"
  | "EMPLOYER_VIEWED_BY_ADMIN"
  | "EMPLOYER_UPDATED"
  | "EMPLOYER_BLOCKED"
  | "EMPLOYER_UNBLOCKED"
  | "EMPLOYER_SUBSCRIPTION_UPDATED"
  | "EMPLOYER_SUBSCRIPTION_PAYMENT_REQUESTED"
  | "SETTINGS_UPDATED"
  | "PIX_SETTINGS_UPDATED"
  | "SUBSCRIPTION_PAYMENT_SETTINGS_UPDATED"
  | "JOB_FUNCTION_CREATED"
  | "JOB_FUNCTION_UPDATED"
  | "JOB_FUNCTION_ACTIVATED"
  | "JOB_FUNCTION_DEACTIVATED"
  | "SUBSCRIPTION_ACTIVATED_7_DAYS"
  | "CANDIDATE_DETAIL_VIEWED"
  | "CANDIDATE_VIEWED_BY_ADMIN"
  | "CANDIDATE_UPDATED"
  | "CANDIDATE_INACTIVATED"
  | "CANDIDATE_REACTIVATED"
  | "CANDIDATE_ANONYMIZED"
  | "CANDIDATE_PROCESS_STARTED"
  | "CANDIDATE_HIRED_CONFIRMED"
  | "CANDIDATE_RETURNED_TO_AVAILABLE"
  | "JOB_OPENING_CREATED"
  | "JOB_OPENING_PAUSED"
  | "JOB_OPENING_RESUMED"
  | "JOB_OPENING_CLOSED"
  | "JOB_OPENING_CANCELED"
  | "CANDIDATE_RESERVED_FOR_JOB_OPENING"
  | "CANDIDATE_RESERVATION_CANCELED"
  | "CANDIDATE_RESERVATION_HIRING_CONFIRMED"
  | "PASSWORD_RESET_REQUESTED"
  | "PASSWORD_RESET_COMPLETED";

export type CreateAuditLogInput = {
  userId?: string;
  action: SensitiveAction | string;
  entity: string;
  entityId?: string;
  metadata?: Prisma.InputJsonValue;
};


