import type { Prisma } from "@prisma/client";

export type SensitiveAction =
  | "ADMIN_LOGIN"
  | "EMPLOYER_REGISTERED"
  | "EMPLOYER_ACCOUNT_UPDATED"
  | "EMPLOYER_PASSWORD_CHANGED"
  | "CANDIDATE_REGISTERED_WITH_CONSENT"
  | "LGPD_REQUEST_CREATED"
  | "MANUAL_PIX_PAYMENT_CREATED"
  | "ADMIN_USER_CREATED"
  | "ADMIN_USER_ROLE_UPDATED"
  | "ADMIN_USER_BLOCKED"
  | "ADMIN_USER_UNBLOCKED"
  | "EMPLOYER_VIEWED_BY_ADMIN"
  | "EMPLOYER_UPDATED"
  | "EMPLOYER_BLOCKED"
  | "EMPLOYER_UNBLOCKED"
  | "EMPLOYER_SUBSCRIPTION_UPDATED"
  | "SETTINGS_UPDATED"
  | "PIX_SETTINGS_UPDATED"
  | "SUBSCRIPTION_PAYMENT_SETTINGS_UPDATED"
  | "OPERATIONAL_REPASSE_SETTINGS_UPDATED"
  | "OPERATIONAL_REPASSE_PAID"
  | "MAINTENANCE_PLAN_PAYMENT_CONFIRMED"
  | "DEVELOPER_COMMISSION_CREATED"
  | "DEVELOPER_COMMISSION_PAID"
  | "DEVELOPER_COMMISSION_CANCELED"
  | "DEVELOPER_COMMISSION_RATE_CHANGED"
  | "JOB_FUNCTION_CREATED"
  | "JOB_FUNCTION_UPDATED"
  | "JOB_FUNCTION_ACTIVATED"
  | "JOB_FUNCTION_DEACTIVATED"
  | "SUBSCRIPTION_ACTIVATED_7_DAYS"
  | "CANDIDATE_DETAIL_VIEWED";

export type CreateAuditLogInput = {
  userId?: string;
  action: SensitiveAction | string;
  entity: string;
  entityId?: string;
  metadata?: Prisma.InputJsonValue;
};
