ALTER TABLE `Employer` ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `LgpdRequest`
  MODIFY `type` ENUM('ACCESS', 'CORRECTION', 'DELETE_REVIEW', 'REVOCATION') NOT NULL;

ALTER TABLE `LgpdRequest`
  ADD COLUMN `status` ENUM('PENDING', 'IN_REVIEW', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
  
  ALTER TABLE `LgpdRequest`
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);