ALTER TABLE `Payment`
  ADD COLUMN `provider` VARCHAR(191) NOT NULL DEFAULT 'manual_pix',
  ADD COLUMN `paidAt` DATETIME(3) NULL,
  MODIFY `status` ENUM('RECORDED', 'PAID', 'USED') NOT NULL DEFAULT 'RECORDED';
